settings:
    trusted_mail_suffix: [
        "sluz.ch"
    ]
    logs: "/../logs/"

db:
    server_ip : "185.101.158.55"
    db : "Registration"
    table : "registration"
    user: "register"

credentials:
    password_db:  "**************"
    password_web: "**************"
    mcpassword:   "***************"

